###
POST http://localhost:9000/api/claims HTTP/1.1
Content-Type: application/json

{
  "nombre": "Manuel Sevilla",
  "dni": "79215156",
  "email": "manuel.5156@email.com",
  "asesor": "Rodrigo Salvador Eguire",
  "reclamo": "No se me ha renovado el servicio de mi celular a pesar de que el pago ya se realizo",
  "fecha": "11-11-2021"
}

###
GET http://localhost:9000/api/claims HTTP/1.1

###
GET http://localhost:9000/api/claims/618d9e719a9c5725c07cbdb5 HTTP/1.1

###
DELETE http://localhost:9000/api/claims/618d9e719a9c5725c07cbdb5 HTTP/1.1

###
PUT http://localhost:9000/api/claims/618d9e719a9c5725c07cbdb5 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Manuel Barbados",
  "dni": "87415961",
  "email": "manuel.652554@email.com",
  "asesor": "Rodrigo ",
  "reclamo": "Aun no se me ha renovado el servicio de mi celular a pesar de que el pago ya se realizo",
  "fecha": "12-11-2021"
}
